name: Run CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Starting containers with docker compose
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: run docker ps
        run : docker ps -a
        
      - name: run netstat 
        run : netstat -tulpn
      
      - name: test curl 80
        run: curl localhost
        
      - name: test curl 9090
        run: curl localhost:9090
        
      - name: test curl 9090 in hit-tracker container
        run: docker exec -it hit-tracker curl localhost:9090/ping
      
      - name: Run functional tests
        run:  go clean -testcache && go test -v test/main_test.go 
        
      - name: Docker stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
